In [1]:
import pandas as pd

In [2]:
data=pd.read_csv('expanded_gift_recommendation_dataset.csv')

In [3]:
data

,user_id,age,gender,relationship_to_receiver,occasion,budget,interests,receiver_personality,receiver_age_group,gift_type,gift_name,product_price,rating,is_top_selling,small_business,relationship_closeness,giver_preference_style,gift_meaningfulness
0,1,41,Female,Partner,Anniversary,3623,Travel,Emotional,Child,Book,Motivational Book,3864,2,Yes,No,very close,practical,Medium
1,2,59,Female,Teacher,Valentine's Day,585,Travel,Creative,Teen,Home Decor,Aroma Diffuser,734,4,No,No,distant,luxury,Low
2,3,46,Male,Family,Valentine's Day,1334,Gaming,Emotional,Senior,Grooming Set,Beard Grooming Kit,1239,4,No,No,close,practical,Medium
3,4,47,Female,Teacher,Birthday,2399,Music,Creative,Child,Toy,Remote Car,2195,4,Yes,Yes,distant,fun,Medium
4,5,32,Male,Teacher,Farewell,4646,Gaming,Extrovert,Teen,Electronics,Smart Watch,4657,4,No,No,distant,practical,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,20,Female,Colleague,Farewell,4967,Fashion,Introvert,Child,Book,Self-help Book,4955,1,Yes,No,neutral,practical,Low
9996,9997,59,Male,Teacher,Birthday,415,Fashion,Practical,Teen,Handmade Craft,Handcrafted Candle,691,4,Yes,Yes,distant,sentimental,Medium
9997,9998,50,Male,Family,Anniversary,721,Tech,Introvert,Teen,Fashion Item,Wrist Watch,519,1,No,No,close,luxury,Low
9998,9999,32,Female,Family,Farewell,3423,Home Decor,Creative,Senior,Toy,LEGO Set,3719,4,No,No,very close,fun,High
9999,10000,37,Female,Partner,Farewell,1805,Gaming,Practical,Adult,Home Decor,Mini Indoor Plant,2082,5,Yes,Yes,very close,luxury,Medium

In [4]:
# delete the  unused feature

In [5]:
data.drop(columns=['user_id','age'],axis=1,inplace=True)

In [6]:
data

,gender,relationship_to_receiver,occasion,budget,interests,receiver_personality,receiver_age_group,gift_type,gift_name,product_price,rating,is_top_selling,small_business,relationship_closeness,giver_preference_style,gift_meaningfulness
0,Female,Partner,Anniversary,3623,Travel,Emotional,Child,Book,Motivational Book,3864,2,Yes,No,very close,practical,Medium
1,Female,Teacher,Valentine's Day,585,Travel,Creative,Teen,Home Decor,Aroma Diffuser,734,4,No,No,distant,luxury,Low
2,Male,Family,Valentine's Day,1334,Gaming,Emotional,Senior,Grooming Set,Beard Grooming Kit,1239,4,No,No,close,practical,Medium
3,Female,Teacher,Birthday,2399,Music,Creative,Child,Toy,Remote Car,2195,4,Yes,Yes,distant,fun,Medium
4,Male,Teacher,Farewell,4646,Gaming,Extrovert,Teen,Electronics,Smart Watch,4657,4,No,No,distant,practical,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,Female,Colleague,Farewell,4967,Fashion,Introvert,Child,Book,Self-help Book,4955,1,Yes,No,neutral,practical,Low
9996,Male,Teacher,Birthday,415,Fashion,Practical,Teen,Handmade Craft,Handcrafted Candle,691,4,Yes,Yes,distant,sentimental,Medium
9997,Male,Family,Anniversary,721,Tech,Introvert,Teen,Fashion Item,Wrist Watch,519,1,No,No,close,luxury,Low
9998,Female,Family,Farewell,3423,Home Decor,Creative,Senior,Toy,LEGO Set,3719,4,No,No,very close,fun,High
9999,Female,Partner,Farewell,1805,Gaming,Practical,Adult,Home Decor,Mini Indoor Plant,2082,5,Yes,Yes,very close,luxury,Medium

In [7]:
data.isnull().sum()

gender                      0
relationship_to_receiver    0
occasion                    0
budget                      0
interests                   0
receiver_personality        0
receiver_age_group          0
gift_type                   0
gift_name                   0
product_price               0
rating                      0
is_top_selling              0
small_business              0
relationship_closeness      0
giver_preference_style      0
gift_meaningfulness         0
dtype: int64

In [8]:
data.describe()

             budget  product_price        rating
count  10000.000000   10000.000000  10000.000000
mean    2569.722300    2565.235600      2.981400
std     1412.510437    1400.226963      1.390916
min      200.000000     202.000000      1.000000
25%     1391.000000    1398.000000      2.000000
50%     2545.000000    2569.000000      3.000000
75%     3788.000000    3784.000000      4.000000
max     4993.000000    4999.000000      5.000000

In [9]:
data['budget']=pd.cut(data['budget'],bins=[0,500,1000,3000,5000],labels=['below_500','500_to_1000','1000_to_3000','3000_to_5000'])

In [10]:
data.head(5)

,gender,relationship_to_receiver,occasion,budget,interests,receiver_personality,receiver_age_group,gift_type,gift_name,product_price,rating,is_top_selling,small_business,relationship_closeness,giver_preference_style,gift_meaningfulness
0,Female,Partner,Anniversary,3000_to_5000,Travel,Emotional,Child,Book,Motivational Book,3864,2,Yes,No,very close,practical,Medium
1,Female,Teacher,Valentine's Day,500_to_1000,Travel,Creative,Teen,Home Decor,Aroma Diffuser,734,4,No,No,distant,luxury,Low
2,Male,Family,Valentine's Day,1000_to_3000,Gaming,Emotional,Senior,Grooming Set,Beard Grooming Kit,1239,4,No,No,close,practical,Medium
3,Female,Teacher,Birthday,1000_to_3000,Music,Creative,Child,Toy,Remote Car,2195,4,Yes,Yes,distant,fun,Medium
4,Male,Teacher,Farewell,3000_to_5000,Gaming,Extrovert,Teen,Electronics,Smart Watch,4657,4,No,No,distant,practical,Low

In [11]:
# - check the  null value(fill the null values) 
# - delete thee unwanted feature

In [12]:
data.columns

Index(['gender', 'relationship_to_receiver', 'occasion', 'budget', 'interests',
       'receiver_personality', 'receiver_age_group', 'gift_type', 'gift_name',
       'product_price', 'rating', 'is_top_selling', 'small_business',
       'relationship_closeness', 'giver_preference_style',
       'gift_meaningfulness'],
      dtype='object')

In [13]:
data['relationship_to_receiver'].value_counts()

relationship_to_receiver
Friend       2114
Colleague    1988
Teacher      1975
Partner      1969
Family       1954
Name: count, dtype: int64

In [14]:
data.drop('small_business',axis=1,inplace=True)

In [15]:
# # encoding
# gender-binary encoding
# relationship_to_receiver-hot encoding
# occasion- hot encoding
# budget_as_catagorical- map
# interests-hot encoding
# receiver_personality-hot encoding
# gift_type-lable encoding
# gift_name-lable encoding
# receiver_age_group-map
# relationship_closeness-map
# giver_preference_style-hot encoding

In [16]:
data.columns

Index(['gender', 'relationship_to_receiver', 'occasion', 'budget', 'interests',
       'receiver_personality', 'receiver_age_group', 'gift_type', 'gift_name',
       'product_price', 'rating', 'is_top_selling', 'relationship_closeness',
       'giver_preference_style', 'gift_meaningfulness'],
      dtype='object')

In [17]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import LabelBinarizer
lb=LabelBinarizer()
le=LabelEncoder()
data['gender']=lb.fit_transform(data['gender'])
data=pd.get_dummies(data,columns=['occasion','receiver_personality','relationship_to_receiver','interests','giver_preference_style'])
budget_map={'below_500':0,'500_to_1000':1,'1000_to_3000':2,'3000_to_5000':3}
data['budget']=data['budget'].map(budget_map)
data['gift_type']=le.fit_transform(data['gift_type'])
data['gift_name']=le.fit_transform(data['gift_name'])
receiver_age_group_map={'Child':0,'Teen':1,'Adult':2,'Senior':3}
data['receiver_age_group']=data['receiver_age_group'].map(receiver_age_group_map)
relationship_closeness_map={'distant':0,'neutral':1,'close':2,'very close':3}
data['relationship_closeness']=data['relationship_closeness'].map(relationship_closeness_map)

In [18]:
data

,gender,budget,receiver_age_group,gift_type,gift_name,product_price,rating,is_top_selling,relationship_closeness,gift_meaningfulness,...,interests_Fitness,interests_Gaming,interests_Home Decor,interests_Music,interests_Tech,interests_Travel,giver_preference_style_fun,giver_preference_style_luxury,giver_preference_style_practical,giver_preference_style_sentimental
0,0,3,0,1,16,3864,2,Yes,3,Medium,...,False,False,False,False,False,True,False,False,True,False
1,0,1,1,6,0,734,4,No,0,Low,...,False,False,False,False,False,True,False,True,False,False
2,1,2,3,4,1,1239,4,No,2,Medium,...,False,True,False,False,False,False,False,False,True,False
3,0,2,0,8,22,2195,4,Yes,0,Medium,...,False,False,False,True,False,False,True,False,False,False
4,1,3,1,2,28,4657,4,No,0,Low,...,False,True,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,0,3,0,1,25,4955,1,Yes,1,Low,...,False,False,False,False,False,False,False,False,True,False
9996,1,0,1,5,11,691,4,Yes,0,Medium,...,False,False,False,False,False,False,False,False,False,True
9997,1,1,1,3,34,519,1,No,2,Low,...,False,False,False,False,True,False,False,True,False,False
9998,0,3,3,8,14,3719,4,No,3,High,...,False,False,True,False,False,False,True,False,False,False
9999,0,2,2,6,15,2082,5,Yes,3,Medium,...,False,True,False,False,False,False,False,True,False,False

In [19]:
data.columns

Index(['gender', 'budget', 'receiver_age_group', 'gift_type', 'gift_name',
       'product_price', 'rating', 'is_top_selling', 'relationship_closeness',
       'gift_meaningfulness', 'occasion_Anniversary', 'occasion_Birthday',
       'occasion_Farewell', 'occasion_Festival', 'occasion_Graduation',
       'occasion_Valentine's Day', 'receiver_personality_Creative',
       'receiver_personality_Emotional', 'receiver_personality_Extrovert',
       'receiver_personality_Introvert', 'receiver_personality_Practical',
       'relationship_to_receiver_Colleague', 'relationship_to_receiver_Family',
       'relationship_to_receiver_Friend', 'relationship_to_receiver_Partner',
       'relationship_to_receiver_Teacher', 'interests_Art', 'interests_Books',
       'interests_Fashion', 'interests_Fitness', 'interests_Gaming',
       'interests_Home Decor', 'interests_Music', 'interests_Tech',
       'interests_Travel', 'giver_preference_style_fun',
       'giver_preference_style_luxury', 'giver_preference_style_practical',
       'giver_preference_style_sentimental'],
      dtype='object')

In [20]:
data['budget'].isnull().sum()

np.int64(0)

In [21]:
gift_type_data=data.drop(columns=['gift_name','product_price','rating','is_top_selling','gift_meaningfulness'])

In [22]:
gift_type_data.columns

Index(['gender', 'budget', 'receiver_age_group', 'gift_type',
       'relationship_closeness', 'occasion_Anniversary', 'occasion_Birthday',
       'occasion_Farewell', 'occasion_Festival', 'occasion_Graduation',
       'occasion_Valentine's Day', 'receiver_personality_Creative',
       'receiver_personality_Emotional', 'receiver_personality_Extrovert',
       'receiver_personality_Introvert', 'receiver_personality_Practical',
       'relationship_to_receiver_Colleague', 'relationship_to_receiver_Family',
       'relationship_to_receiver_Friend', 'relationship_to_receiver_Partner',
       'relationship_to_receiver_Teacher', 'interests_Art', 'interests_Books',
       'interests_Fashion', 'interests_Fitness', 'interests_Gaming',
       'interests_Home Decor', 'interests_Music', 'interests_Tech',
       'interests_Travel', 'giver_preference_style_fun',
       'giver_preference_style_luxury', 'giver_preference_style_practical',
       'giver_preference_style_sentimental'],
      dtype='object')

In [23]:
gift_type_data=gift_type_data.astype(int)

In [24]:
gift_type_data

,gender,budget,receiver_age_group,gift_type,relationship_closeness,occasion_Anniversary,occasion_Birthday,occasion_Farewell,occasion_Festival,occasion_Graduation,...,interests_Fitness,interests_Gaming,interests_Home Decor,interests_Music,interests_Tech,interests_Travel,giver_preference_style_fun,giver_preference_style_luxury,giver_preference_style_practical,giver_preference_style_sentimental
0,0,3,0,1,3,1,0,0,0,0,...,0,0,0,0,0,1,0,0,1,0
1,0,1,1,6,0,0,0,0,0,0,...,0,0,0,0,0,1,0,1,0,0
2,1,2,3,4,2,0,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
3,0,2,0,8,0,0,1,0,0,0,...,0,0,0,1,0,0,1,0,0,0
4,1,3,1,2,0,0,0,1,0,0,...,0,1,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,0,3,0,1,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
9996,1,0,1,5,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,1
9997,1,1,1,3,2,1,0,0,0,0,...,0,0,0,0,1,0,0,1,0,0
9998,0,3,3,8,3,0,0,1,0,0,...,0,0,1,0,0,0,1,0,0,0
9999,0,2,2,6,3,0,0,1,0,0,...,0,1,0,0,0,0,0,1,0,0

In [25]:
x_type=gift_type_data.drop('gift_type',axis=1)

In [26]:
y_type=gift_type_data['gift_type']

In [27]:
x_type.columns

Index(['gender', 'budget', 'receiver_age_group', 'relationship_closeness',
       'occasion_Anniversary', 'occasion_Birthday', 'occasion_Farewell',
       'occasion_Festival', 'occasion_Graduation', 'occasion_Valentine's Day',
       'receiver_personality_Creative', 'receiver_personality_Emotional',
       'receiver_personality_Extrovert', 'receiver_personality_Introvert',
       'receiver_personality_Practical', 'relationship_to_receiver_Colleague',
       'relationship_to_receiver_Family', 'relationship_to_receiver_Friend',
       'relationship_to_receiver_Partner', 'relationship_to_receiver_Teacher',
       'interests_Art', 'interests_Books', 'interests_Fashion',
       'interests_Fitness', 'interests_Gaming', 'interests_Home Decor',
       'interests_Music', 'interests_Tech', 'interests_Travel',
       'giver_preference_style_fun', 'giver_preference_style_luxury',
       'giver_preference_style_practical',
       'giver_preference_style_sentimental'],
      dtype='object')

In [28]:
y_type

0       1
1       6
2       4
3       8
4       2
       ..
9995    1
9996    5
9997    3
9998    8
9999    6
Name: gift_type, Length: 10000, dtype: int64

In [29]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x_type,y_type,test_size=0.20,random_state=42)

In [31]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report
rc_model=RandomForestClassifier(n_estimators=300,random_state=42)
rc_model.fit(x_train,y_train)
rc_pred=rc_model.predict(x_test)
print(accuracy_score(y_test,rc_pred))
print(classification_report(y_test,rc_pred))

0.992
              precision    recall  f1-score   support

           0       0.97      0.98      0.98       239
           1       1.00      1.00      1.00       231
           2       1.00      1.00      1.00       208
           3       0.99      1.00      0.99       251
           4       1.00      1.00      1.00       248
           5       1.00      1.00      1.00       208
           6       1.00      0.99      0.99       250
           7       1.00      1.00      1.00       179
           8       0.97      0.97      0.97       186

    accuracy                           0.99      2000
   macro avg       0.99      0.99      0.99      2000
weighted avg       0.99      0.99      0.99      2000

In [32]:
rc_model.score(x_test,y_test)

0.992

In [33]:
rc_model.score(x_train,y_train)

0.996625

In [34]:
gift_type_data

,gender,budget,receiver_age_group,gift_type,relationship_closeness,occasion_Anniversary,occasion_Birthday,occasion_Farewell,occasion_Festival,occasion_Graduation,...,interests_Fitness,interests_Gaming,interests_Home Decor,interests_Music,interests_Tech,interests_Travel,giver_preference_style_fun,giver_preference_style_luxury,giver_preference_style_practical,giver_preference_style_sentimental
0,0,3,0,1,3,1,0,0,0,0,...,0,0,0,0,0,1,0,0,1,0
1,0,1,1,6,0,0,0,0,0,0,...,0,0,0,0,0,1,0,1,0,0
2,1,2,3,4,2,0,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
3,0,2,0,8,0,0,1,0,0,0,...,0,0,0,1,0,0,1,0,0,0
4,1,3,1,2,0,0,0,1,0,0,...,0,1,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,0,3,0,1,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
9996,1,0,1,5,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,1
9997,1,1,1,3,2,1,0,0,0,0,...,0,0,0,0,1,0,0,1,0,0
9998,0,3,3,8,3,0,0,1,0,0,...,0,0,1,0,0,0,1,0,0,0
9999,0,2,2,6,3,0,0,1,0,0,...,0,1,0,0,0,0,0,1,0,0

In [35]:
gift_name_data=gift_type_data
gift_name_data['gift_name']=data['gift_name']

In [36]:
gift_name_data.columns

Index(['gender', 'budget', 'receiver_age_group', 'gift_type',
       'relationship_closeness', 'occasion_Anniversary', 'occasion_Birthday',
       'occasion_Farewell', 'occasion_Festival', 'occasion_Graduation',
       'occasion_Valentine's Day', 'receiver_personality_Creative',
       'receiver_personality_Emotional', 'receiver_personality_Extrovert',
       'receiver_personality_Introvert', 'receiver_personality_Practical',
       'relationship_to_receiver_Colleague', 'relationship_to_receiver_Family',
       'relationship_to_receiver_Friend', 'relationship_to_receiver_Partner',
       'relationship_to_receiver_Teacher', 'interests_Art', 'interests_Books',
       'interests_Fashion', 'interests_Fitness', 'interests_Gaming',
       'interests_Home Decor', 'interests_Music', 'interests_Tech',
       'interests_Travel', 'giver_preference_style_fun',
       'giver_preference_style_luxury', 'giver_preference_style_practical',
       'giver_preference_style_sentimental', 'gift_name'],
      dtype='object')

In [37]:
x_name=gift_name_data.drop('gift_name',axis=1)

In [38]:
y_name=gift_name_data['gift_name']

In [39]:
from sklearn.model_selection import train_test_split
x1_train,x1_test,y1_train,y1_test=train_test_split(x_name,y_name,test_size=0.20,random_state=42)

In [40]:
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier
rfc_model=rfc(n_estimators=300,random_state=42)
rfc_model.fit(x1_train,y1_train)
rfc_pred=rfc_model.predict(x1_test)
print(accuracy_score(y1_test,rfc_pred))
print(classification_report(y1_test,rfc_pred))

0.9985
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        70
           1       1.00      1.00      1.00        90
           2       1.00      1.00      1.00        43
           3       1.00      1.00      1.00        78
           4       1.00      1.00      1.00        58
           5       1.00      1.00      1.00        50
           6       1.00      1.00      1.00        39
           7       1.00      0.94      0.97        53
           8       1.00      1.00      1.00        66
           9       1.00      1.00      1.00        74
          10       1.00      1.00      1.00        37
          11       1.00      1.00      1.00        60
          12       1.00      1.00      1.00        59
          13       1.00      1.00      1.00        23
          14       1.00      1.00      1.00        36
          15       1.00      1.00      1.00        97
          16       1.00      1.00      1.00        40
          17       0.95      1.00      0.98        60
          18       1.00      1.00      1.00        66
          19       1.00      1.00      1.00        71
          20       1.00      1.00      1.00        46
          21       1.00      1.00      1.00        65
          22       1.00      1.00      1.00        42
          23       1.00      1.00      1.00        47
          24       1.00      1.00      1.00        49
          25       1.00      1.00      1.00        68
          26       1.00      1.00      1.00        87
          27       1.00      1.00      1.00        64
          28       1.00      1.00      1.00        59
          29       1.00      1.00      1.00        43
          30       1.00      1.00      1.00        41
          31       1.00      1.00      1.00        37
          32       1.00      1.00      1.00        83
          33       1.00      1.00      1.00        63
          34       1.00      1.00      1.00        36

    accuracy                           1.00      2000
   macro avg       1.00      1.00      1.00      2000
weighted avg       1.00      1.00      1.00      2000

In [41]:
rfc_model.score(x1_test,y1_test)

0.9985

In [42]:
rfc_model.score(x1_train,y1_train)

0.999

In [43]:
x_name

,gender,budget,receiver_age_group,gift_type,relationship_closeness,occasion_Anniversary,occasion_Birthday,occasion_Farewell,occasion_Festival,occasion_Graduation,...,interests_Fitness,interests_Gaming,interests_Home Decor,interests_Music,interests_Tech,interests_Travel,giver_preference_style_fun,giver_preference_style_luxury,giver_preference_style_practical,giver_preference_style_sentimental
0,0,3,0,1,3,1,0,0,0,0,...,0,0,0,0,0,1,0,0,1,0
1,0,1,1,6,0,0,0,0,0,0,...,0,0,0,0,0,1,0,1,0,0
2,1,2,3,4,2,0,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
3,0,2,0,8,0,0,1,0,0,0,...,0,0,0,1,0,0,1,0,0,0
4,1,3,1,2,0,0,0,1,0,0,...,0,1,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,0,3,0,1,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
9996,1,0,1,5,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,1
9997,1,1,1,3,2,1,0,0,0,0,...,0,0,0,0,1,0,0,1,0,0
9998,0,3,3,8,3,0,0,1,0,0,...,0,0,1,0,0,0,1,0,0,0
9999,0,2,2,6,3,0,0,1,0,0,...,0,1,0,0,0,0,0,1,0,0

In [44]:
gift_type_data

,gender,budget,receiver_age_group,gift_type,relationship_closeness,occasion_Anniversary,occasion_Birthday,occasion_Farewell,occasion_Festival,occasion_Graduation,...,interests_Gaming,interests_Home Decor,interests_Music,interests_Tech,interests_Travel,giver_preference_style_fun,giver_preference_style_luxury,giver_preference_style_practical,giver_preference_style_sentimental,gift_name
0,0,3,0,1,3,1,0,0,0,0,...,0,0,0,0,1,0,0,1,0,16
1,0,1,1,6,0,0,0,0,0,0,...,0,0,0,0,1,0,1,0,0,0
2,1,2,3,4,2,0,0,0,0,0,...,1,0,0,0,0,0,0,1,0,1
3,0,2,0,8,0,0,1,0,0,0,...,0,0,1,0,0,1,0,0,0,22
4,1,3,1,2,0,0,0,1,0,0,...,1,0,0,0,0,0,0,1,0,28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,0,3,0,1,1,0,0,1,0,0,...,0,0,0,0,0,0,0,1,0,25
9996,1,0,1,5,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,11
9997,1,1,1,3,2,1,0,0,0,0,...,0,0,0,1,0,0,1,0,0,34
9998,0,3,3,8,3,0,0,1,0,0,...,0,1,0,0,0,1,0,0,0,14
9999,0,2,2,6,3,0,0,1,0,0,...,1,0,0,0,0,0,1,0,0,15

In [45]:
x_type.columns

Index(['gender', 'budget', 'receiver_age_group', 'relationship_closeness',
       'occasion_Anniversary', 'occasion_Birthday', 'occasion_Farewell',
       'occasion_Festival', 'occasion_Graduation', 'occasion_Valentine's Day',
       'receiver_personality_Creative', 'receiver_personality_Emotional',
       'receiver_personality_Extrovert', 'receiver_personality_Introvert',
       'receiver_personality_Practical', 'relationship_to_receiver_Colleague',
       'relationship_to_receiver_Family', 'relationship_to_receiver_Friend',
       'relationship_to_receiver_Partner', 'relationship_to_receiver_Teacher',
       'interests_Art', 'interests_Books', 'interests_Fashion',
       'interests_Fitness', 'interests_Gaming', 'interests_Home Decor',
       'interests_Music', 'interests_Tech', 'interests_Travel',
       'giver_preference_style_fun', 'giver_preference_style_luxury',
       'giver_preference_style_practical',
       'giver_preference_style_sentimental'],
      dtype='object')

In [46]:
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
rc_model=RandomForestClassifier(n_estimators=300,random_state=42)
rc_model.fit(x_train,y_train)
rc_pred=rc_model.predict(x_test)
rfc=RandomForestClassifier
rfc_model=rfc(n_estimators=300,random_state=42)
rfc_model.fit(x1_train,y1_train)
rfc_pred=rfc_model.predict(x1_test)
class encoding:
    def lable_encode(self,gender,age,relationship_closeness,budget):
        self.gender_encode=0 if gender == 'Female' else 1
        self.age_map={'Child':0,'Teen':1,'Adult':2,'Senior':3}
        self.age_encode=self.age_map[age]
        self.relationship_map={'distant':0,'neutral':1,'close':2,'very close':3}
        self.relationship_encoding=self.relationship_map[relationship_closeness]
        self.budget_encode={'below_500':0,'500_to_1000':1,'1000_to_3000':2,'3000_to_5000':3}
        self.budget_map=self.budget_encode[budget]
    def hot_encode_occ(self,name):
        self.value={
        'occ_Graduation':0,
        'occ_Farewell':0,
        'occ_Anniversary':0,
        'occ_Birthday':0,
        "occ_Valentine's Day":0,
        'occ_Festival':0
        }
        self.value[f'occ_{name}']=1
        self.occ_set=[self.value["occ_Graduation"],
            self.value["occ_Farewell"],
            self.value["occ_Anniversary"],
            self.value["occ_Birthday"],  
            self.value["occ_Valentine's Day"],
            self.value["occ_Festival"]]
    def hot_encode_receiver_per(self,name):
        self.value={
            'rec_Creative':0,
            'rec_Emotional':0,
            'rec_Introvert':0,
            'rec_Extrovert':0,
            'rec_Practical':0
        }
        self.value[f'rec_{name}']=1
        self.rec_set=[self.value["rec_Creative"],
            self.value["rec_Emotional"],
            self.value["rec_Introvert"],
            self.value["rec_Extrovert"],
            self.value["rec_Practical"]]
    def hot_encode_relationship_to_rec(self,name):
        self.value={
        'rel_Colleague':0,
        'rel_Friend':0,
        'rel_Teacher':0,
        'rel_Partner':0,
        'rel_Family':0
        }
        self.value[f'rel_{name}']=1
        self.rel_set=[self.value["rel_Colleague"],
            self.value["rel_Friend"],
            self.value["rel_Teacher"],
            self.value["rel_Partner"],
            self.value["rel_Family"]]
    def hot_encode_interests(self,name):
        self.value={
        'int_Gaming':0,
        'int_Home Decor':0,
        'int_Fashion':0,
        'int_Books':0,
        'int_Tech':0,
        'int_Travel':0,
        'int_Art':0,
        'int_Fitness':0,
        'int_Music':0
        }
        self.value[f'int_{name}']=1
        self.int_set=[self.value["int_Gaming"],
            self.value["int_Home Decor"],
            self.value["int_Fashion"],
            self.value["int_Books"],
            self.value["int_Tech"],
            self.value["int_Travel"],
            self.value["int_Art"],
            self.value["int_Fitness"],
            self.value["int_Music"]]
    def hot_encode_giver_preference_style(self,name):
        self.value={
        'style_practical':0,
        'style_luxury':0,
        'style_fun':0,
        'style_sentimental':0
        }
        self.value[f'style_{name}']=1
        self.style_set=[self.value["style_practical"],
            self.value["style_luxury"],
            self.value["style_fun"],
            self.value["style_sentimental"]]
    def df_value1(self,):
        self.gift_type=pd.DataFrame({'gender':[self.gender_encode],'budget':[self.budget_map],'receiver_age_group':[self.age_encode],'relationship_closeness':[self.relationship_encoding],'occasion_Anniversary':self.occ_set[2],'occasion_Birthday':self.occ_set[3],'occasion_Farewell':self.occ_set[1],'occasion_Festival':self.occ_set[5],'occasion_Graduation':self.occ_set[0],"occasion_Valentine's Day":self.occ_set[4],
        'receiver_personality_Creative':self.rec_set[0],'receiver_personality_Emotional':self.rec_set[1],
       'receiver_personality_Extrovert':self.rec_set[3],'receiver_personality_Introvert':self.rec_set[2],
       'receiver_personality_Practical':self.rec_set[4],'relationship_to_receiver_Colleague':self.rel_set[0],
       'relationship_to_receiver_Family':self.rel_set[4],'relationship_to_receiver_Friend':self.rel_set[1],
       'relationship_to_receiver_Partner':self.rel_set[3],'relationship_to_receiver_Teacher':self.rel_set[2],
       'interests_Art':self.int_set[6],'interests_Books':self.int_set[3],'interests_Fashion':self.int_set[2],
       'interests_Fitness':self.int_set[7],'interests_Gaming':self.int_set[0],'interests_Home Decor':self.int_set[1],
       'interests_Music':self.int_set[8],'interests_Tech':self.int_set[4],'interests_Travel':self.int_set[5],
       'giver_preference_style_fun':self.style_set[2],'giver_preference_style_luxury':self.style_set[1],
       'giver_preference_style_practical':self.style_set[0],
       'giver_preference_style_sentimental':self.style_set[3]})
    def value1_pred(self):
        self.gift_type = self.gift_type[rc_model.feature_names_in_]
        self.probs = rc_model.predict_proba(self.gift_type)
        self.sample_probs = self.probs[0]
        self.top4_indices = np.argsort(self.sample_probs)[::-1][:4]
        self.top4_classes = rc_model.classes_[self.top4_indices]
        self.top4_probs = self.sample_probs[self.top4_indices]
        self.empty1 = []
        for i in range(4):
            self.empty1.append(self.top4_probs[i])
        self.empty = []
        self.gift_type_dict = {0:'Accessory',1:'Book',2:'Electronics',3:'Fashion Item',4:'Grooming Set',5:'Handmade Craft',6:'Home Decor',7:'Personalized Gift',8:'Toy'}
        for j in self.top4_classes:
            self.empty.append(self.gift_type_dict[j])
        for k in range(4):
            print(f'{self.empty[k]} : {round(self.empty1[k], 3)} --> {k}')
        print(f'These are the types recommended for your {relationship} with probability:')
        self.choose_type = int(input('Choose any one (ex: 0, 1, 2, 3): '))
        self.type_name = self.empty[self.choose_type]
        self.keys = [k for k, v in self.gift_type_dict.items() if v == self.type_name]
        self.convert_type_df = pd.DataFrame([{'gift_type': self.keys[0]}])
    def value2_pred(self):
        self.result = pd.concat([self.gift_type, self.convert_type_df], axis=1)
        self.result = self.result[rfc_model.feature_names_in_]
        self.probs1 = rfc_model.predict_proba(self.result)
        self.sample_probs1 = self.probs1[0]
        self.tops4_gift = np.argsort(self.sample_probs1)[::-1][:4]
        self.top4_classes1 = rfc_model.classes_[self.tops4_gift]
        self.top4_probs1 = self.sample_probs1[self.tops4_gift]
        gift_name = {15:'Mini Indoor Plant',32:'Wall Art Frame',26:'Skincare Kit',1:'Beard Grooming Kit',0:'Aroma Diffuser',8:'Engraved Pen',19:'Perfume Set',17:'Name Printed Mug',3:'Bracelet',9:'Fiction Novel',25:'Self-help Book',21:'Puzzle Game',33:'Wallet',7:'Customized Photo Frame',18:'Neck Chain',4:'Cap',28:'Smart Watch',5:'Clay Art Pot',12:'Handmade Greeting Card',11:'Handcrafted Candle',24:'Science Guide',27:'Sling Bag',23:'Scarf',20:'Portable Speaker',30:'Stylish T-shirt',31:'Sunglasses',29:'Soft Toy',16:'Motivational Book',34:'Wrist Watch',2:'Bluetooth Earbuds',10:'Fitness Band',14:'LEGO Set',22:'Remote Car',6:'Customized Keychain',13:'LED Table Lamp'}
        print('\nTop 4 Recommended Gifts:')
        for i in self.top4_classes1:
            print(f'🎁 {gift_name[i]}')
print('wecome to the gift reccamendeted system')
name=input('enter the reciver name')
gender=input(f'tell me {name} gender').capitalize()
age=input(f'tell me {name} age group (Child/Teen/Adult/Senior)').capitalize()
relationship_closeness=input(f'tell me relatioship with {name} (distant/neutral/close/very close)').lower()
budget=input(f'tell me your bedget on the gift(below_500/500_to_1000/1000_to_3000/3000_to_5000)').lower()
occasion=input(f"tell me the occasion(Graduation/Farewell/Anniversary/Birthday/Valentine's Day/Festival)").capitalize()
receiver_personality=input(f'tell me about {name} personality(Creative/Emotional/Introvert/Extrovert/Practical)').capitalize()
relationship=input(f'tell me your relationship with {name} (Friend/Colleague/Teacher/Partner/Family)').capitalize()
interests=input(f'tell me what{name} interested(Gaming/Home Decor/Fashion/Books/Tech/Travel/Art/Fitness/Music)').capitalize()
giver_preference=input(f'what you preference(practical/luxury/fun/sentimental)').lower()
obj=encoding()
obj.lable_encode(gender,age,relationship_closeness,budget)
obj.hot_encode_occ(occasion)
obj.hot_encode_receiver_per(receiver_personality)
obj.hot_encode_relationship_to_rec(relationship)
obj.hot_encode_interests(interests)
obj.hot_encode_giver_preference_style(giver_preference)
obj.df_value1()
obj.value1_pred()
obj.value2_pred()

wecome to the gift reccamendeted system

enter the reciver name vishva
tell me vishva gender male
tell me vishva age group (Child/Teen/Adult/Senior) Teen
tell me relatioship with vishva (distant/neutral/close/very close) very close
tell me your bedget on the gift(below_500/500_to_1000/1000_to_3000/3000_to_5000) 1000_to_3000
tell me the occasion(Graduation/Farewell/Anniversary/Birthday/Valentine's Day/Festival) Festival
tell me about vishva personality(Creative/Emotional/Introvert/Extrovert/Practical) Practical
tell me your relationship with vishva (Friend/Colleague/Teacher/Partner/Family) Friend
tell me whatvishva interested(Gaming/Home Decor/Fashion/Books/Tech/Travel/Art/Fitness/Music) Music
what you preference(practical/luxury/fun/sentimental) fun

Accessory : 0.643 --> 0
Toy : 0.29 --> 1
Handmade Craft : 0.027 --> 2
Home Decor : 0.02 --> 3
These are the types recommended for your Friend with probability:

Choose any one (ex: 0, 1, 2, 3):  0

Top 4 Recommended Gifts:
🎁 Neck Chain
🎁 Sunglasses
🎁 Cap
🎁 Bracelet